spring.application.name=gym-api
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB:gym_db}
spring.datasource.username=${POSTGRES_USER:gym}
spring.datasource.password=${POSTGRES_PASSWORD:gym_password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=8090
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never